// ─── Chapter-wise Topics to Learn ───────────────────────────────────────────
// Detailed sub-topics for each chapter across JEE/NEET syllabus

export function getChapterTopics(chapter: string): string[] {
  return TOPICS_BANK[chapter] || ['Topics will be updated soon'];
}

const TOPICS_BANK: Record<string, string[]> = {

  // ════════════════════════ PHYSICS ════════════════════════

  'Physics and Measurement': [
    'SI Units and Dimensions',
    'Dimensional Analysis and Applications',
    'Significant Figures',
    'Errors in Measurement — Absolute, Relative, Percentage',
    'Instruments — Vernier Caliper, Screw Gauge',
    'Least Count and Zero Error',
    'Dimensional Formulae of Physical Quantities',
    'Limitations of Dimensional Analysis',
  ],

  'Kinematics': [
    'Distance and Displacement',
    'Speed and Velocity',
    'Uniform and Non-uniform Motion',
    'Equations of Motion (SUVAT)',
    'Motion under Gravity — Free Fall',
    'Relative Motion in 1D and 2D',
    'Projectile Motion — Range, Height, Time of Flight',
    'Projectile on Inclined Plane',
    'Circular Motion — Angular Velocity, Centripetal Acceleration',
    'Graphs — s-t, v-t, a-t interpretation',
  ],

  'Laws of Motion': [
    'Newton\'s First Law — Inertia',
    'Newton\'s Second Law — F = ma',
    'Newton\'s Third Law — Action-Reaction Pairs',
    'Free Body Diagrams (FBD)',
    'Friction — Static, Kinetic, Rolling',
    'Angle of Friction and Angle of Repose',
    'Motion on Inclined Planes (with/without friction)',
    'Connected Bodies and Pulley Systems',
    'Pseudo Forces in Non-Inertial Frames',
    'Impulse and Momentum',
    'Conservation of Linear Momentum',
    'Circular Motion Dynamics — Banking of Roads',
  ],

  'Work, Energy, and Power': [
    'Work Done by Constant and Variable Forces',
    'Work-Energy Theorem',
    'Kinetic Energy and Potential Energy',
    'Conservative and Non-conservative Forces',
    'Potential Energy of a Spring',
    'Power — Instantaneous and Average',
    'Collisions — Elastic and Inelastic',
    'Coefficient of Restitution',
    'Energy Conservation in Systems',
    'Work done by Friction',
  ],

  'Rotational Motion': [
    'Angular Displacement, Velocity, and Acceleration',
    'Torque and Moment of Force',
    'Moment of Inertia — Discrete and Continuous Bodies',
    'Parallel and Perpendicular Axis Theorems',
    'MOI of Standard Shapes (Ring, Disc, Sphere, Rod, Cylinder)',
    'Angular Momentum and Conservation',
    'Rotational Kinetic Energy',
    'Rolling without Slipping',
    'Combined Translational and Rotational Motion',
    'Equilibrium of Rigid Bodies',
    'Centre of Mass and its Motion',
  ],

  'Gravitation': [
    'Newton\'s Law of Universal Gravitation',
    'Gravitational Field and Potential',
    'Acceleration due to Gravity and its Variation (height, depth, latitude)',
    'Gravitational Potential Energy',
    'Orbital Velocity and Escape Velocity',
    'Kepler\'s Laws of Planetary Motion',
    'Satellites — Geostationary, Polar',
    'Binding Energy of Satellites',
    'Weightlessness',
  ],

  'Properties of Solids and Liquids': [
    'Elastic Behaviour — Stress, Strain, Hooke\'s Law',
    'Young\'s Modulus, Bulk Modulus, Shear Modulus',
    'Pressure in Fluids — Pascal\'s Law',
    'Archimedes\' Principle and Buoyancy',
    'Viscosity — Stokes\' Law, Terminal Velocity',
    'Surface Tension — Capillarity, Angle of Contact',
    'Bernoulli\'s Theorem and Applications',
    'Equation of Continuity',
    'Streamline and Turbulent Flow',
    'Thermal Expansion — Linear, Area, Volume',
    'Calorimetry and Specific Heat',
    'Heat Transfer — Conduction, Convection, Radiation',
    'Newton\'s Law of Cooling',
    'Stefan-Boltzmann Law',
  ],

  'Thermodynamics': [
    'Thermal Equilibrium and Zeroth Law',
    'First Law of Thermodynamics',
    'Work Done in Thermodynamic Processes',
    'Isothermal Process',
    'Adiabatic Process',
    'Isochoric and Isobaric Processes',
    'Cyclic Process and PV Diagrams',
    'Heat Engines — Carnot Cycle',
    'Refrigerators and Heat Pumps',
    'Second Law of Thermodynamics',
    'Entropy and its Interpretation',
    'Reversible and Irreversible Processes',
  ],

  'Kinetic Theory of Gases': [
    'Ideal Gas Equation (PV = nRT)',
    'Kinetic Theory Assumptions',
    'Pressure from Molecular Motion',
    'RMS, Average, and Most Probable Speeds',
    'Degrees of Freedom',
    'Law of Equipartition of Energy',
    'Specific Heat Capacities (Cp, Cv)',
    'Mean Free Path',
    'Real Gases — Van der Waals Equation',
  ],

  'Oscillations and Waves': [
    'Simple Harmonic Motion (SHM) — Definition and Examples',
    'Displacement, Velocity, Acceleration in SHM',
    'Energy in SHM',
    'Time Period of Spring-Mass System',
    'Simple Pendulum',
    'Damped and Forced Oscillations',
    'Resonance',
    'Wave Motion — Transverse and Longitudinal',
    'Speed of Sound in Different Media',
    'Superposition Principle',
    'Standing Waves — Nodes and Antinodes',
    'Beats',
    'Doppler Effect in Sound',
    'Organ Pipes — Open and Closed',
    'Harmonics and Overtones',
  ],

  'Electrostatics': [
    'Electric Charge — Properties, Conservation',
    'Coulomb\'s Law',
    'Electric Field — Point Charges and Distributions',
    'Electric Field Lines',
    'Electric Dipole — Field and Torque',
    'Gauss\'s Law and Applications',
    'Electric Potential and Potential Energy',
    'Equipotential Surfaces',
    'Capacitance — Parallel Plate Capacitor',
    'Dielectrics and Polarisation',
    'Capacitors in Series and Parallel',
    'Energy Stored in a Capacitor',
    'Van de Graaff Generator',
  ],

  'Current Electricity': [
    'Electric Current and Current Density',
    'Ohm\'s Law and Resistance',
    'Resistivity and its Temperature Dependence',
    'Colour Code for Resistors',
    'Series and Parallel Combinations',
    'EMF and Internal Resistance of a Cell',
    'Kirchhoff\'s Laws — Junction and Loop Rules',
    'Wheatstone Bridge',
    'Metre Bridge and Potentiometer',
    'Electrical Power and Energy',
    'Drift Velocity and Mobility',
  ],

  'Magnetic Effects of Current and Magnetism': [
    'Biot-Savart Law',
    'Magnetic Field due to a Straight Conductor',
    'Ampere\'s Circuital Law',
    'Solenoid and Toroid',
    'Force on a Current-Carrying Conductor in Magnetic Field',
    'Force between Two Parallel Conductors',
    'Torque on a Current Loop — Magnetic Dipole',
    'Moving Coil Galvanometer',
    'Magnetic Materials — Para, Dia, Ferro',
    'Hysteresis',
    'Earth\'s Magnetism — Declination, Inclination',
  ],

  'Electromagnetic Induction and Alternating Currents': [
    'Faraday\'s Laws of Electromagnetic Induction',
    'Lenz\'s Law',
    'Motional EMF',
    'Eddy Currents',
    'Self and Mutual Inductance',
    'AC Generator',
    'AC Circuits — R, L, C, LR, RC, LCR',
    'Impedance and Phase Angle',
    'Resonance in LCR Circuit',
    'Power in AC Circuits — Power Factor',
    'Transformers — Step Up, Step Down',
    'LC Oscillations',
  ],

  'Electromagnetic Waves': [
    'Displacement Current',
    'Maxwell\'s Equations (qualitative)',
    'Electromagnetic Spectrum',
    'Properties of EM Waves',
    'Applications of Different EM Waves',
    'Radio, Micro, IR, Visible, UV, X-ray, Gamma',
  ],

  'Optics': [
    'Reflection — Laws, Plane and Spherical Mirrors',
    'Mirror Formula and Magnification',
    'Refraction — Snell\'s Law',
    'Total Internal Reflection',
    'Optical Fibres',
    'Lenses — Convex, Concave, Lens Maker\'s Equation',
    'Power and Combination of Lenses',
    'Prism — Refraction, Minimum Deviation',
    'Dispersion of Light — Spectrum',
    'Scattering of Light — Rayleigh, Tyndall',
    'Human Eye — Defects and Correction',
    'Microscope and Telescope',
    'Young\'s Double Slit Experiment — Interference',
    'Diffraction — Single Slit',
    'Polarisation — Brewster\'s Law, Malus\' Law',
  ],

  'Dual Nature of Matter and Radiation': [
    'Photoelectric Effect',
    'Einstein\'s Photoelectric Equation',
    'Photon — Energy and Momentum',
    'de Broglie Wavelength',
    'Davisson-Germer Experiment',
    'Wave-Particle Duality',
    'Work Function and Threshold Frequency',
  ],

  'Atoms and Nuclei': [
    'Rutherford\'s Model and Alpha Scattering',
    'Bohr\'s Model — Energy Levels, Spectra',
    'Hydrogen Spectrum — Lyman, Balmer, Paschen Series',
    'Composition of Nucleus — Protons, Neutrons',
    'Nuclear Size and Density',
    'Mass-Energy Relation (E = mc²)',
    'Mass Defect and Binding Energy',
    'Binding Energy Curve',
    'Radioactivity — α, β, γ Decay',
    'Half-life and Decay Law',
    'Nuclear Fission and Fusion',
    'Nuclear Reactor',
  ],

  'Electronic Devices': [
    'Semiconductors — Intrinsic and Extrinsic',
    'p-type and n-type Semiconductors',
    'p-n Junction Diode — Forward and Reverse Bias',
    'I-V Characteristics of Diode',
    'Diode as Rectifier — Half Wave, Full Wave',
    'Zener Diode — Voltage Regulator',
    'Photodiode, LED, Solar Cell',
    'Transistor — npn, pnp, Action',
    'Transistor as Switch and Amplifier',
    'Logic Gates — OR, AND, NOT, NAND, NOR',
  ],

  'Experimental Skills': [
    'Vernier Calipers and Screw Gauge',
    'Simple Pendulum — g Determination',
    'Young\'s Modulus — Searle\'s Apparatus',
    'Specific Heat — Method of Mixtures',
    'Speed of Sound — Resonance Tube',
    'Ohm\'s Law Verification',
    'Metre Bridge and Potentiometer',
    'Focal Length of Mirrors and Lenses',
    'Refractive Index of Glass Slab',
    'Diode and Transistor Characteristics',
  ],

  // ════════════════════════ CHEMISTRY ════════════════════════

  'Some Basic Concepts in Chemistry': [
    'Matter and its Classification',
    'Dalton\'s Atomic Theory',
    'Laws of Chemical Combination',
    'Mole Concept and Avogadro\'s Number',
    'Molar Mass and Molecular Mass',
    'Empirical and Molecular Formulae',
    'Stoichiometry and Balanced Equations',
    'Limiting Reagent',
    'Concentration Terms — Molarity, Molality, Mole Fraction, ppm',
    'Percentage Composition and Yield',
  ],

  'Atomic Structure': [
    'Thomson, Rutherford, and Bohr Models',
    'Quantum Mechanical Model',
    'Quantum Numbers — n, l, m, s',
    'Shapes of Orbitals — s, p, d, f',
    'Aufbau Principle',
    'Pauli Exclusion Principle',
    'Hund\'s Rule',
    'Electronic Configuration of Elements',
    'de Broglie\'s Hypothesis',
    'Heisenberg\'s Uncertainty Principle',
    'Photoelectric Effect and Spectra',
  ],

  'Chemical Bonding and Molecular Structure': [
    'Ionic Bond — Lattice Energy, Born-Haber Cycle',
    'Covalent Bond — Lewis Structure',
    'VSEPR Theory',
    'Valence Bond Theory',
    'Hybridisation — sp, sp², sp³, sp³d, sp³d²',
    'Molecular Orbital Theory',
    'Bond Order, Bond Length, Bond Energy',
    'Hydrogen Bonding',
    'Resonance',
    'Coordinate Bond',
    'Metallic Bond',
    'Polarity and Dipole Moment',
    'Fajan\'s Rules',
  ],

  'Chemical Thermodynamics': [
    'System, Surroundings, State Functions',
    'First Law of Thermodynamics',
    'Internal Energy and Enthalpy',
    'Hess\'s Law',
    'Standard Enthalpy of Formation, Combustion, Neutralisation',
    'Bond Enthalpy',
    'Entropy and Spontaneity',
    'Gibbs Free Energy',
    'ΔG and Equilibrium Constant',
    'Thermochemical Equations',
  ],

  'Solutions': [
    'Types of Solutions',
    'Concentration Units — Molarity, Molality, Mole Fraction, Mass %',
    'Solubility — Factors Affecting',
    'Henry\'s Law',
    'Raoult\'s Law — Ideal and Non-ideal Solutions',
    'Colligative Properties — RLVP, BPE, FPD, Osmotic Pressure',
    'Van\'t Hoff Factor',
    'Abnormal Molar Mass — Association, Dissociation',
    'Vapour Pressure of Solutions',
  ],

  'Equilibrium': [
    'Law of Mass Action',
    'Equilibrium Constant — Kc and Kp',
    'Le Chatelier\'s Principle',
    'Factors Affecting Equilibrium',
    'Ionic Equilibrium in Solutions',
    'Acids, Bases — Arrhenius, Brønsted-Lowry, Lewis',
    'pH Scale and Calculations',
    'Buffer Solutions — Henderson-Hasselbalch Equation',
    'Solubility Product (Ksp)',
    'Common Ion Effect',
    'Ionisation of Weak Acids and Bases',
    'Hydrolysis of Salts',
  ],

  'Redox Reactions': [
    'Oxidation and Reduction — Electron Transfer',
    'Oxidation Number Rules',
    'Balancing Redox Reactions — Ion-Electron Method',
    'Types of Redox Reactions — Combination, Decomposition, Displacement, Disproportionation',
    'Electrode Potential',
    'Electrochemical Series',
  ],

  'Electrochemistry': [
    'Electrolytic and Galvanic Cells',
    'Electrode Potential — Standard Hydrogen Electrode',
    'Nernst Equation',
    'Electrolysis — Faraday\'s Laws',
    'Conductance — Specific, Molar, Equivalent',
    'Kohlrausch\'s Law',
    'Batteries — Primary, Secondary (Lead-Acid, Li-ion)',
    'Fuel Cells',
    'Corrosion and Prevention',
  ],

  'Chemical Kinetics': [
    'Rate of Reaction — Average and Instantaneous',
    'Factors Affecting Rate — Conc, Temp, Catalyst, Surface Area',
    'Rate Law and Rate Constant',
    'Order of Reaction — Zero, First, Second',
    'Molecularity',
    'Integrated Rate Equations',
    'Half-life of Reactions',
    'Arrhenius Equation — Activation Energy',
    'Collision Theory',
    'Catalysis — Homogeneous, Heterogeneous, Enzyme',
  ],

  'Classification of Elements and Periodicity': [
    'Modern Periodic Law',
    'Long Form of the Periodic Table',
    'Classification — s, p, d, f Blocks',
    'Periodic Trends — Atomic Radius',
    'Periodic Trends — Ionisation Enthalpy',
    'Periodic Trends — Electron Gain Enthalpy',
    'Periodic Trends — Electronegativity',
    'Periodic Trends — Metallic/Non-metallic Character',
    'Diagonal Relationship',
    'Anomalous Properties of First Elements',
  ],

  'p-Block Elements': [
    'Group 13 — Boron Family',
    'Group 14 — Carbon Family',
    'Group 15 — Nitrogen Family',
    'Group 16 — Oxygen Family (Chalcogens)',
    'Group 17 — Halogens',
    'Group 18 — Noble Gases',
    'Allotropy — Carbon, Phosphorus, Sulphur',
    'Oxoacids of Nitrogen, Phosphorus, Sulphur, Halogens',
    'Interhalogen Compounds',
    'Important Compounds — Borax, Boric Acid, Silicones, Ozone',
  ],

  'd- and f-Block Elements': [
    'General Properties of Transition Elements',
    'Electronic Configuration of 3d, 4d, 5d Series',
    'Oxidation States and Trends',
    'Colour of Transition Metal Ions',
    'Magnetic Properties',
    'Catalytic Properties',
    'Interstitial Compounds',
    'Alloy Formation',
    'Important Compounds — KMnO₄, K₂Cr₂O₇',
    'Lanthanoids and Actinoids',
    'Lanthanoid Contraction',
  ],

  'Coordination Compounds': [
    'Werner\'s Theory',
    'IUPAC Nomenclature',
    'Coordination Number and Oxidation State',
    'Isomerism — Geometric, Optical, Linkage, Ionisation',
    'Valence Bond Theory for Coordination Compounds',
    'Crystal Field Theory (CFT)',
    'Crystal Field Splitting (Octahedral, Tetrahedral)',
    'Colour and Magnetic Properties from CFT',
    'Stability of Coordination Compounds',
    'Applications — EDTA, Cis-platin, Hemoglobin',
  ],

  'Purification and Characterisation of Organic Compounds': [
    'Methods of Purification — Crystallisation, Distillation, Chromatography',
    'Sublimation and Differential Extraction',
    'Qualitative Analysis — Detection of C, H, N, S, Halogens',
    'Quantitative Analysis — Estimation of Elements',
    'Determination of Molecular Formula',
    'Empirical Formula from Combustion Data',
  ],

  'Basic Principles of Organic Chemistry': [
    'Hybridisation and Shape of Organic Molecules',
    'Structural and Stereoisomerism',
    'IUPAC Nomenclature',
    'Electronic Effects — Inductive, Resonance, Hyperconjugation',
    'Electromeric Effect',
    'Homolytic and Heterolytic Bond Fission',
    'Carbocations, Carbanions, Free Radicals, Carbenes',
    'Types of Organic Reactions — Substitution, Addition, Elimination, Rearrangement',
    'Reaction Intermediates',
    'Acid-Base Strength in Organic Chemistry',
  ],

  'Hydrocarbons': [
    'Alkanes — Preparation, Properties, Combustion, Halogenation',
    'Alkenes — Preparation, Markovnikov\'s Rule, Peroxide Effect',
    'Alkynes — Preparation, Acidic Character',
    'Benzene — Structure, Aromaticity, Hückel\'s Rule',
    'Electrophilic Aromatic Substitution',
    'Directive Influence of Substituents',
    'Conformations of Ethane and Butane',
    'Geometric Isomerism (cis-trans)',
  ],

  'Organic Compounds Containing Halogens': [
    'Classification — Alkyl, Aryl, Allylic, Benzylic Halides',
    'Preparation from Alcohols, Alkenes, Hydrocarbons',
    'SN1 and SN2 Mechanisms',
    'Elimination Reactions — E1 and E2',
    'Grignard Reagents',
    'Organometallic Compounds',
    'Polyhalogen Compounds — CHCl₃, CCl₄, Freons, DDT',
    'Environmental Effects of Halogen Compounds',
  ],

  'Organic Compounds Containing Oxygen': [
    'Alcohols — Classification, Preparation, Reactions',
    'Phenols — Acidity, Electrophilic Substitution',
    'Ethers — Preparation, Reactions',
    'Aldehydes — Preparation, Nucleophilic Addition',
    'Ketones — Preparation, Reactions',
    'Carboxylic Acids — Preparation, Acidity, Reactions',
    'Acid Derivatives — Esters, Acid Halides, Anhydrides, Amides',
    'Cannizzaro, Aldol, Cross-Aldol Reactions',
    'Tollens\' and Fehling\'s Tests',
    'Distinction Tests for Aldehydes and Ketones',
  ],

  'Organic Compounds Containing Nitrogen': [
    'Amines — Classification, Preparation, Basicity',
    'Primary, Secondary, Tertiary Amines',
    'Gabriel Phthalimide Synthesis',
    'Hofmann Bromamide Reaction',
    'Diazotisation and Coupling Reactions',
    'Cyanides and Isocyanides',
    'Nitro Compounds — Preparation, Reduction',
    'Diazonium Salts and their Reactions',
  ],

  'Biomolecules': [
    'Carbohydrates — Mono, Di, Polysaccharides',
    'Glucose and Fructose — Structure',
    'Mutarotation',
    'Proteins — Amino Acids, Peptide Bond',
    'Primary, Secondary, Tertiary, Quaternary Structure',
    'Enzymes — Classification, Mechanism, Specificity',
    'Nucleic Acids — DNA and RNA Structure',
    'Vitamins — Classification, Deficiency Diseases',
    'Hormones — Types and Functions',
    'Lipids — Fats, Oils, Waxes',
  ],

  'Principles Related to Practical Chemistry': [
    'Detection of Extra Elements (N, S, Halogens)',
    'Detection of Functional Groups — OH, CHO, COOH, NH₂',
    'Preparation of Organic Compounds',
    'Qualitative Inorganic Analysis — Cation and Anion Tests',
    'Volumetric Analysis — Acid-Base, Redox Titrations',
    'Salt Analysis',
  ],

  // ════════════════════════ MATHEMATICS ════════════════════════

  'Sets, Relations, and Functions': [
    'Types of Sets — Finite, Infinite, Empty, Universal',
    'Subsets and Power Set',
    'Union, Intersection, Complement, Difference',
    'Venn Diagrams',
    'De Morgan\'s Laws',
    'Cartesian Product',
    'Relations — Reflexive, Symmetric, Transitive, Equivalence',
    'Types of Functions — One-one, Onto, Bijective',
    'Composition of Functions',
    'Inverse Functions',
  ],

  'Complex Numbers and Quadratic Equations': [
    'Algebra of Complex Numbers — Addition, Multiplication, Division',
    'Modulus and Argument',
    'Argand Plane',
    'Polar and Euler Form',
    'De Moivre\'s Theorem',
    'Cube Roots of Unity',
    'Quadratic Equations — Discriminant, Nature of Roots',
    'Sum and Product of Roots',
    'Formation of Equations from Roots',
    'Locus Problems using Complex Numbers',
  ],

  'Matrices and Determinants': [
    'Types of Matrices — Square, Diagonal, Identity, Null, Symmetric',
    'Matrix Operations — Addition, Multiplication, Transpose',
    'Determinants — 2×2, 3×3 Evaluation',
    'Properties of Determinants',
    'Cofactors and Adjoint',
    'Inverse of a Matrix',
    'Solving Linear Equations — Cramer\'s Rule, Matrix Method',
    'Rank of a Matrix',
    'Consistency of Linear Systems',
  ],

  'Permutations and Combinations': [
    'Fundamental Principle of Counting',
    'Permutations — nPr Formula',
    'Permutations with Repetition',
    'Circular Permutations',
    'Combinations — nCr Formula',
    'Properties of Combinations',
    'Division into Groups',
    'Derangements',
    'Applications in Probability',
  ],

  'Binomial Theorem and its Simple Applications': [
    'Binomial Expansion for Positive Integer n',
    'General Term and Middle Term',
    'Properties of Binomial Coefficients',
    'Multinomial Theorem',
    'Binomial Theorem for Rational Index',
    'Applications — Approximations, Divisibility',
  ],

  'Sequence and Series': [
    'Arithmetic Progression (AP) — nth Term, Sum',
    'Geometric Progression (GP) — nth Term, Sum, Infinite GP',
    'Harmonic Progression (HP)',
    'Arithmetic-Geometric Series',
    'Relation between AM, GM, HM',
    'Sum of Special Series — Σn, Σn², Σn³',
    'Telescoping Series',
    'Method of Differences',
  ],

  'Limit, Continuity, and Differentiability': [
    'Limits — Algebraic, Trigonometric, Exponential, Logarithmic',
    'L\'Hôpital\'s Rule',
    'Squeeze Theorem',
    'Continuity — Definition, Types of Discontinuity',
    'Intermediate Value Theorem',
    'Differentiability and its Relation with Continuity',
    'Derivatives — First Principles, Chain Rule, Product Rule, Quotient Rule',
    'Implicit and Parametric Differentiation',
    'Higher Order Derivatives',
    'Applications — Maxima, Minima, Rate of Change',
    'Mean Value Theorems — Rolle\'s, Lagrange\'s',
    'Tangents and Normals',
    'Increasing and Decreasing Functions',
    'Curve Sketching',
  ],

  'Integral Calculus': [
    'Indefinite Integrals — Basic Formulae',
    'Integration by Substitution',
    'Integration by Parts (LIATE)',
    'Integration by Partial Fractions',
    'Trigonometric Integrals and Substitutions',
    'Definite Integrals — Properties',
    'Fundamental Theorem of Calculus',
    'Area under Curves',
    'Area between Curves',
    'Reduction Formulae',
    'Improper Integrals (basics)',
  ],

  'Differential Equations': [
    'Order and Degree of ODE',
    'Formation of Differential Equations',
    'Variable Separable Method',
    'Homogeneous Differential Equations',
    'Linear Differential Equations — Integrating Factor',
    'Bernoulli\'s Equation',
    'Applications — Growth/Decay, Newton\'s Cooling, RL/RC Circuits',
    'Orthogonal Trajectories',
  ],

  'Coordinate Geometry': [
    'Distance, Section, and Midpoint Formulae',
    'Straight Lines — Slope, Intercept, General Form',
    'Angle between Lines, Parallel and Perpendicular Lines',
    'Distance of a Point from a Line',
    'Family of Lines',
    'Pair of Straight Lines',
    'Circle — Standard and General Equation',
    'Tangent and Normal to a Circle',
    'Parabola — Standard Forms, Focus, Directrix',
    'Ellipse — Standard Form, Eccentricity, Foci',
    'Hyperbola — Standard Form, Asymptotes',
    'Chord of Contact and Pole-Polar',
  ],

  'Three-Dimensional Geometry': [
    'Coordinate Axes and Planes in 3D',
    'Distance between Two Points',
    'Section Formula in 3D',
    'Direction Cosines and Direction Ratios',
    'Equation of a Line — Symmetric and Parametric',
    'Angle between Two Lines',
    'Equation of a Plane — Normal and Intercept Form',
    'Angle between Line and Plane',
    'Distance of a Point from a Plane',
    'Coplanarity of Lines',
    'Skew Lines — Shortest Distance',
  ],

  'Vector Algebra': [
    'Vectors — Types, Unit Vector, Position Vector',
    'Addition, Subtraction, Scalar Multiplication',
    'Dot Product — Properties, Angle between Vectors',
    'Cross Product — Properties, Area of Parallelogram/Triangle',
    'Scalar Triple Product — Volume of Parallelepiped',
    'Vector Triple Product',
    'Coplanarity Condition',
    'Section Formula using Vectors',
    'Projection of a Vector',
  ],

  'Statistics and Probability': [
    'Mean, Median, Mode',
    'Variance and Standard Deviation',
    'Mean Deviation',
    'Probability — Classical, Axiomatic',
    'Conditional Probability',
    'Multiplication Theorem',
    'Independent Events',
    'Bayes\' Theorem',
    'Random Variable — Discrete, Continuous',
    'Binomial Distribution — Mean and Variance',
    'Bernoulli Trials',
  ],

  'Trigonometry': [
    'Trigonometric Ratios and Identities',
    'Compound Angles — sin(A±B), cos(A±B), tan(A±B)',
    'Multiple and Sub-Multiple Angles',
    'Sum-to-Product and Product-to-Sum',
    'Trigonometric Equations — General Solutions',
    'Inverse Trigonometric Functions — Domain, Range',
    'Properties of Inverse Trig Functions',
    'Heights and Distances',
    'Sine, Cosine, and Tangent Rules',
    'Area of Triangle using Trigonometry',
  ],

  // ════════════════════════ BIOLOGY ════════════════════════

  'Diversity in Living World': [
    'What is Living? — Characteristics of Life',
    'Biodiversity and Need for Classification',
    'Taxonomy and Systematics',
    'Taxonomic Hierarchy — Species to Kingdom',
    'Binomial Nomenclature — Rules',
    'Five Kingdom Classification — Whittaker',
    'Kingdom Monera — Bacteria, Archaebacteria, Cyanobacteria',
    'Kingdom Protista — Chrysophytes, Dinoflagellates, Euglenoids, Slime Moulds, Protozoans',
    'Kingdom Fungi — Phycomycetes, Ascomycetes, Basidiomycetes, Deuteromycetes',
    'Kingdom Plantae — Classification',
    'Kingdom Animalia — Classification up to Phyla',
    'Viruses, Viroids, Prions, Lichens',
  ],

  'Structural Organisation in Animals and Plants': [
    'Morphology of Flowering Plants — Root, Stem, Leaf, Flower, Fruit, Seed',
    'Plant Tissues — Meristematic and Permanent',
    'Simple Tissues — Parenchyma, Collenchyma, Sclerenchyma',
    'Complex Tissues — Xylem and Phloem',
    'Animal Tissues — Epithelial, Connective, Muscular, Neural',
    'Anatomy of Dicot and Monocot Root, Stem, Leaf',
    'Secondary Growth',
    'Morphology and Anatomy of Earthworm, Cockroach, Frog',
  ],

  'Cell Structure and Function': [
    'Cell Theory — Schleiden, Schwann',
    'Prokaryotic vs Eukaryotic Cells',
    'Cell Envelope — Cell Wall, Cell Membrane (Fluid Mosaic Model)',
    'Endomembrane System — ER, Golgi, Lysosomes, Vacuoles',
    'Mitochondria — Structure and Function',
    'Plastids — Chloroplast Structure',
    'Ribosomes — Structure',
    'Cytoskeleton — Microfilaments, Microtubules, Intermediate Filaments',
    'Nucleus — Nuclear Envelope, Chromatin, Nucleolus',
    'Cell Cycle — Phases (G1, S, G2, M)',
    'Mitosis — Stages and Significance',
    'Meiosis — Stages, Crossing Over, Significance',
    'Biomolecules — Carbohydrates, Proteins, Lipids, Nucleic Acids',
    'Enzymes — Properties, Classification, Mechanism',
  ],

  'Plant Physiology': [
    'Transport in Plants — Diffusion, Osmosis, Plasmolysis',
    'Water Potential and Movement',
    'Absorption of Water — Apoplast and Symplast Pathways',
    'Transpiration — Mechanism, Factors, Stomatal Regulation',
    'Translocation of Sugars — Pressure Flow Hypothesis',
    'Mineral Nutrition — Essential Elements, Deficiency Symptoms',
    'Nitrogen Cycle and Nitrogen Fixation',
    'Photosynthesis — Light Reactions, Calvin Cycle',
    'Photorespiration and C4 Pathway',
    'Respiration — Glycolysis, TCA Cycle, Electron Transport Chain',
    'Fermentation',
    'Plant Growth and Development — Auxins, Gibberellins, Cytokinins, ABA, Ethylene',
    'Photoperiodism and Vernalisation',
  ],

  'Human Physiology': [
    'Digestion and Absorption — Alimentary Canal, Digestive Glands',
    'Digestive Enzymes and their Actions',
    'Absorption — Small Intestine, Large Intestine',
    'Breathing and Exchange of Gases — Respiratory System',
    'Mechanism of Breathing — Inspiration, Expiration',
    'Gas Exchange — Partial Pressures, O₂-Hb Dissociation Curve',
    'Respiratory Volumes and Capacities',
    'Body Fluids and Circulation — Blood Composition',
    'Heart — Structure, Cardiac Cycle, ECG',
    'Blood Vessels — Arteries, Veins, Capillaries',
    'Blood Pressure and its Regulation',
    'Lymphatic System',
    'Excretory Products and Elimination — Nephron Structure and Function',
    'Urine Formation — Ultrafiltration, Reabsorption, Secretion',
    'Counter-current Mechanism',
    'Locomotion and Movement — Skeletal, Muscular System',
    'Mechanism of Muscle Contraction — Sliding Filament Theory',
    'Types of Joints',
    'Neural Control and Coordination — Neuron Structure',
    'Synaptic Transmission',
    'Central Nervous System, Peripheral Nervous System',
    'Reflex Arc',
    'Sense Organs — Eye, Ear',
    'Chemical Coordination — Endocrine Glands and Hormones',
    'Mechanism of Hormone Action',
    'Disorders of Endocrine System',
  ],

  'Reproduction': [
    'Reproduction in Organisms — Asexual and Sexual',
    'Asexual Methods — Binary Fission, Budding, Fragmentation, Sporulation',
    'Sexual Reproduction in Flowering Plants — Flower Structure',
    'Pollination — Self and Cross, Agents',
    'Double Fertilisation',
    'Post-fertilisation Events — Seed, Fruit Development',
    'Apomixis and Polyembryony',
    'Human Reproductive System — Male and Female',
    'Spermatogenesis and Oogenesis',
    'Menstrual Cycle',
    'Fertilisation, Implantation, Embryo Development',
    'Pregnancy and Parturition',
    'Lactation',
    'Reproductive Health — Family Planning, Contraception',
    'STDs — AIDS, Gonorrhoea, Syphilis',
    'Infertility — IVF, GIFT, ZIFT, ICSI',
  ],

  'Genetics and Evolution': [
    'Mendel\'s Laws — Dominance, Segregation, Independent Assortment',
    'Monohybrid and Dihybrid Crosses',
    'Incomplete Dominance and Codominance',
    'Multiple Alleles — ABO Blood Groups',
    'Pleiotropy',
    'Sex Determination — XY and ZW Systems',
    'Sex-linked Inheritance — Colour Blindness, Haemophilia',
    'Linkage and Crossing Over',
    'Chromosomal Theory of Inheritance',
    'DNA — Structure, Replication',
    'Central Dogma — Transcription, Translation',
    'Genetic Code — Properties',
    'Gene Expression and Regulation — Lac Operon',
    'Human Genome Project',
    'DNA Fingerprinting',
    'Mutation — Gene, Chromosomal',
    'Origin of Life — Oparin-Haldane Theory',
    'Evolution — Evidence, Darwin\'s Theory',
    'Natural Selection — Types',
    'Hardy-Weinberg Principle',
    'Adaptive Radiation',
    'Human Evolution',
  ],

  'Biology and Human Welfare': [
    'Health and Disease — Pathogens, Immunity',
    'Innate and Adaptive Immunity',
    'Vaccination and Immunisation',
    'Allergies and Autoimmunity',
    'AIDS — Pathogen, Transmission, Prevention',
    'Cancer — Types, Causes, Treatment',
    'Drugs and Alcohol Abuse',
    'Microbes in Human Welfare — Fermentation, Antibiotics',
    'Biogas Production',
    'Sewage Treatment',
    'Biocontrol Agents and Biofertilisers',
  ],

  'Biotechnology and Its Applications': [
    'Principles of Biotechnology — Genetic Engineering',
    'Tools — Restriction Enzymes, Vectors, Host Organisms',
    'Recombinant DNA Technology — Steps',
    'PCR — Polymerase Chain Reaction',
    'Gel Electrophoresis',
    'Gene Cloning',
    'Applications in Medicine — Insulin, Gene Therapy, Molecular Diagnostics',
    'Transgenic Animals',
    'GM Crops — Bt Cotton, Golden Rice',
    'Bioethics and Biosafety',
    'Biopiracy',
  ],

  'Ecology and Environment': [
    'Organisms and Populations — Abiotic Factors',
    'Population Attributes — Birth Rate, Death Rate, Age Distribution',
    'Population Growth Models — Exponential, Logistic',
    'Population Interactions — Mutualism, Competition, Predation, Parasitism',
    'Ecosystem — Structure and Function',
    'Energy Flow — Food Chain, Food Web, Trophic Levels',
    'Ecological Pyramids — Number, Biomass, Energy',
    'Nutrient Cycling — Carbon and Phosphorus Cycles',
    'Ecological Succession — Primary and Secondary',
    'Biodiversity — Genetic, Species, Ecosystem',
    'Biodiversity Conservation — In-situ, Ex-situ',
    'Hotspots and Threats to Biodiversity',
    'Environmental Issues — Pollution, Deforestation, Global Warming',
    'Ozone Depletion',
    'Waste Management',
  ],
};
